# Generated by CMake 3.6.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
set(boost_all_lib boost_unit_test_framework boost_system boost_date_time boost_thread boost_atomic boost_chrono boost_exception boost_container math_c99 math_c99f math_c99l math_tr1 math_tr1f math_tr1l boost_filesystem boost_random boost_regex boost_timer boost_serialization boost_wserialization boost_graph boost_iostreams boost_locale boost_program_options boost_signals boost_type_erasure boost_wave)
if(PythonLibs_FOUND)
	set(boost_all_lib ${boost_all_lib} boost_python)
endif()
foreach(_expectedTarget ${boost_all_lib})
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target boost_unit_test_framework
add_library(boost_unit_test_framework STATIC IMPORTED)

set_target_properties(boost_unit_test_framework PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_system
add_library(boost_system STATIC IMPORTED)

set_target_properties(boost_system PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_date_time
add_library(boost_date_time STATIC IMPORTED)

set_target_properties(boost_date_time PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_thread
add_library(boost_thread STATIC IMPORTED)

set_target_properties(boost_thread PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB;BOOST_THREAD_BUILD_LIB"
)

# Create imported target boost_atomic
add_library(boost_atomic STATIC IMPORTED)

set_target_properties(boost_atomic PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_chrono
add_library(boost_chrono STATIC IMPORTED)

set_target_properties(boost_chrono PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_exception
add_library(boost_exception STATIC IMPORTED)

set_target_properties(boost_exception PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_container
add_library(boost_container STATIC IMPORTED)

set_target_properties(boost_container PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target math_c99
add_library(math_c99 STATIC IMPORTED)

set_target_properties(math_c99 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target math_c99f
add_library(math_c99f STATIC IMPORTED)

set_target_properties(math_c99f PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target math_c99l
add_library(math_c99l STATIC IMPORTED)

set_target_properties(math_c99l PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target math_tr1
add_library(math_tr1 STATIC IMPORTED)

set_target_properties(math_tr1 PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target math_tr1f
add_library(math_tr1f STATIC IMPORTED)

set_target_properties(math_tr1f PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target math_tr1l
add_library(math_tr1l STATIC IMPORTED)

set_target_properties(math_tr1l PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_filesystem
add_library(boost_filesystem STATIC IMPORTED)

set_target_properties(boost_filesystem PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB;BOOST_ALL_NO_LIB"
)

# Create imported target boost_random
add_library(boost_random STATIC IMPORTED)

set_target_properties(boost_random PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_regex
add_library(boost_regex STATIC IMPORTED)

set_target_properties(boost_regex PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_timer
add_library(boost_timer STATIC IMPORTED)

set_target_properties(boost_timer PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_serialization
add_library(boost_serialization STATIC IMPORTED)

set_target_properties(boost_serialization PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_wserialization
add_library(boost_wserialization STATIC IMPORTED)

set_target_properties(boost_wserialization PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_graph
add_library(boost_graph STATIC IMPORTED)

set_target_properties(boost_graph PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_iostreams
add_library(boost_iostreams STATIC IMPORTED)

# Create imported target boost_locale
add_library(boost_locale STATIC IMPORTED)

set_target_properties(boost_locale PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_program_options
add_library(boost_program_options STATIC IMPORTED)

set_target_properties(boost_program_options PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_signals
add_library(boost_signals STATIC IMPORTED)

set_target_properties(boost_signals PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_type_erasure
add_library(boost_type_erasure STATIC IMPORTED)

set_target_properties(boost_type_erasure PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

# Create imported target boost_wave
add_library(boost_wave STATIC IMPORTED)

set_target_properties(boost_wave PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB"
)

if( PythonLibs_FOUND )
	# Create imported target boost_python
	add_library(boost_python STATIC IMPORTED)
	set_target_properties(boost_python PROPERTIES
	  INTERFACE_COMPILE_DEFINITIONS "BOOST_ALL_NO_LIB;BOOST_PYTHON_STATIC_LIB;BOOST_NUMPY_SOURCE"
	)
endif()

# Import target "boost_unit_test_framework" for configuration "Debug"
set_property(TARGET boost_unit_test_framework APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_unit_test_framework PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_unit_test_frameworkd.lib"
  )

# Import target "boost_system" for configuration "Debug"
set_property(TARGET boost_system APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_system PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_systemd.lib"
  )

# Import target "boost_date_time" for configuration "Debug"
set_property(TARGET boost_date_time APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_date_time PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_date_timed.lib"
  )

# Import target "boost_thread" for configuration "Debug"
set_property(TARGET boost_thread APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_thread PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_date_time"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_threadd.lib"
  )

# Import target "boost_atomic" for configuration "Debug"
set_property(TARGET boost_atomic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_atomic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_atomicd.lib"
  )

# Import target "boost_chrono" for configuration "Debug"
set_property(TARGET boost_chrono APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_chrono PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_exception;boost_system"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_chronod.lib"
  )

# Import target "boost_exception" for configuration "Debug"
set_property(TARGET boost_exception APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_exception PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_exceptiond.lib"
  )

# Import target "boost_container" for configuration "Debug"
set_property(TARGET boost_container APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_container PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_containerd.lib"
  )

# Import target "math_c99" for configuration "Debug"
set_property(TARGET math_c99 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(math_c99 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_math_c99d.lib"
  )

# Import target "math_c99f" for configuration "Debug"
set_property(TARGET math_c99f APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(math_c99f PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_math_c99fd.lib"
  )

# Import target "math_c99l" for configuration "Debug"
set_property(TARGET math_c99l APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(math_c99l PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_math_c99ld.lib"
  )

# Import target "math_tr1" for configuration "Debug"
set_property(TARGET math_tr1 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(math_tr1 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_math_tr1d.lib"
  )

# Import target "math_tr1f" for configuration "Debug"
set_property(TARGET math_tr1f APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(math_tr1f PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_math_tr1fd.lib"
  )

# Import target "math_tr1l" for configuration "Debug"
set_property(TARGET math_tr1l APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(math_tr1l PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_math_tr1ld.lib"
  )

# Import target "boost_filesystem" for configuration "Debug"
set_property(TARGET boost_filesystem APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_filesystem PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_system"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_filesystemd.lib"
  )

# Import target "boost_random" for configuration "Debug"
set_property(TARGET boost_random APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_random PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_system"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_randomd.lib"
  )

# Import target "boost_regex" for configuration "Debug"
set_property(TARGET boost_regex APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_regex PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_regexd.lib"
  )

# Import target "boost_timer" for configuration "Debug"
set_property(TARGET boost_timer APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_timer PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_chrono"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_timerd.lib"
  )

# Import target "boost_serialization" for configuration "Debug"
set_property(TARGET boost_serialization APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_serialization PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_serializationd.lib"
  )

# Import target "boost_wserialization" for configuration "Debug"
set_property(TARGET boost_wserialization APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_wserialization PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_serialization"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_wserializationd.lib"
  )

# Import target "boost_graph" for configuration "Debug"
set_property(TARGET boost_graph APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_graph PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_regex"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_graphd.lib"
  )

# Import target "boost_iostreams" for configuration "Debug"
set_property(TARGET boost_iostreams APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_iostreams PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_iostreamsd.lib"
  )

# Import target "boost_locale" for configuration "Debug"
set_property(TARGET boost_locale APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_locale PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_system"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_localed.lib"
  )

# Import target "boost_program_options" for configuration "Debug"
set_property(TARGET boost_program_options APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_program_options PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_program_optionsd.lib"
  )

# Import target "boost_signals" for configuration "Debug"
set_property(TARGET boost_signals APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_signals PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_signalsd.lib"
  )

# Import target "boost_type_erasure" for configuration "Debug"
set_property(TARGET boost_type_erasure APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_type_erasure PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_thread;boost_system"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_type_erasured.lib"
  )

# Import target "boost_wave" for configuration "Debug"
set_property(TARGET boost_wave APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(boost_wave PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_filesystem;boost_thread;boost_date_time"
  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_waved.lib"
  )

if( PythonLibs_FOUND )
	# Import target "boost_python" for configuration "Debug"
	set_property(TARGET boost_python APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
	set_target_properties(boost_python PROPERTIES
	  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
	  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "boost_serialization;boost_graph;${PYTHON_LIBRARIES}"
	  IMPORTED_LOCATION_DEBUG "${Boost_LIBRARY_DIRS}/boost_pythond.lib"
	  )
endif()
 
# Import target "boost_unit_test_framework" for configuration "Release"
set_property(TARGET boost_unit_test_framework APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_unit_test_framework PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_unit_test_framework.lib"
  )

# Import target "boost_system" for configuration "Release"
set_property(TARGET boost_system APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_system PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_system.lib"
  )

# Import target "boost_date_time" for configuration "Release"
set_property(TARGET boost_date_time APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_date_time PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_date_time.lib"
  )

# Import target "boost_thread" for configuration "Release"
set_property(TARGET boost_thread APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_thread PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_date_time"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_thread.lib"
  )

# Import target "boost_atomic" for configuration "Release"
set_property(TARGET boost_atomic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_atomic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_atomic.lib"
  )

# Import target "boost_chrono" for configuration "Release"
set_property(TARGET boost_chrono APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_chrono PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_exception;boost_system"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_chrono.lib"
  )

# Import target "boost_exception" for configuration "Release"
set_property(TARGET boost_exception APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_exception PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_exception.lib"
  )

# Import target "boost_container" for configuration "Release"
set_property(TARGET boost_container APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_container PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_container.lib"
  )

# Import target "math_c99" for configuration "Release"
set_property(TARGET math_c99 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(math_c99 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_math_c99.lib"
  )

# Import target "math_c99f" for configuration "Release"
set_property(TARGET math_c99f APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(math_c99f PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_math_c99f.lib"
  )

# Import target "math_c99l" for configuration "Release"
set_property(TARGET math_c99l APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(math_c99l PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_math_c99l.lib"
  )

# Import target "math_tr1" for configuration "Release"
set_property(TARGET math_tr1 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(math_tr1 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_math_tr1.lib"
  )

# Import target "math_tr1f" for configuration "Release"
set_property(TARGET math_tr1f APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(math_tr1f PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_math_tr1f.lib"
  )

# Import target "math_tr1l" for configuration "Release"
set_property(TARGET math_tr1l APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(math_tr1l PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_math_tr1l.lib"
  )

# Import target "boost_filesystem" for configuration "Release"
set_property(TARGET boost_filesystem APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_filesystem PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_system"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_filesystem.lib"
  )

# Import target "boost_random" for configuration "Release"
set_property(TARGET boost_random APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_random PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_system"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_random.lib"
  )

# Import target "boost_regex" for configuration "Release"
set_property(TARGET boost_regex APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_regex PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_regex.lib"
  )

# Import target "boost_timer" for configuration "Release"
set_property(TARGET boost_timer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_timer PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_chrono"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_timer.lib"
  )

# Import target "boost_serialization" for configuration "Release"
set_property(TARGET boost_serialization APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_serialization PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_serialization.lib"
  )

# Import target "boost_wserialization" for configuration "Release"
set_property(TARGET boost_wserialization APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_wserialization PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_serialization"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_wserialization.lib"
  )

# Import target "boost_graph" for configuration "Release"
set_property(TARGET boost_graph APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_graph PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_regex"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_graph.lib"
  )

# Import target "boost_iostreams" for configuration "Release"
set_property(TARGET boost_iostreams APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_iostreams PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_iostreams.lib"
  )

# Import target "boost_locale" for configuration "Release"
set_property(TARGET boost_locale APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_locale PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_system"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_locale.lib"
  )

# Import target "boost_program_options" for configuration "Release"
set_property(TARGET boost_program_options APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_program_options PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_program_options.lib"
  )

# Import target "boost_signals" for configuration "Release"
set_property(TARGET boost_signals APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_signals PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_signals.lib"
  )

# Import target "boost_type_erasure" for configuration "Release"
set_property(TARGET boost_type_erasure APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_type_erasure PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_thread;boost_system"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_type_erasure.lib"
  )

# Import target "boost_wave" for configuration "Release"
set_property(TARGET boost_wave APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(boost_wave PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_filesystem;boost_thread;boost_date_time"
  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_wave.lib"
  )

if( PythonLibs_FOUND )
	# Import target "boost_python" for configuration "Release"
	set_property(TARGET boost_python APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
	set_target_properties(boost_python PROPERTIES
	  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
	  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "boost_serialization;boost_graph;${PYTHON_LIBRARIES}"
	  IMPORTED_LOCATION_RELEASE "${Boost_LIBRARY_DIRS}/boost_python.lib"
	  )
endif()

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)

